name: Submodule daily check
on: 
  schedule:
    - cron: "0 0 */1 * *"
  workflow_dispatch:

jobs:
  check:
    name: Submodule check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branches: [master]

    defaults: 
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        ref: ${{ matrix.branches }}
    - name: Create update branch
      run: git checkout -b csupdate/${{ matrix.branches }}
    - name: Initialize mandatory git config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email noreply@github.com
        git config --global pull.rebase false
    - name: Update submodule
      run: |
        cd lib/FFXIVClientStructs
        git pull origin main --allow-unrelated-histories
        cd ../..
        git add lib/FFXIVClientStructs
        git commit --message "Update ClientStructs"
        git push origin csupdate/$${{ matrix.branches }}
    - name: Create PR
      run: |
        gh pr create --head --fill --base ${{ matrix.branches }}
